name: server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.0.5

dependencies:
  filesize: ^2.0.1
  tribbles: ^1.0.1
  lua_dardo: #^0.0.4
    git:
      url: https://github.com/maks/LuaDardo
      ref: main

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
