name: server
description: A highly concurrent WS server built using Isolates Erlang-style
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.0.6

dependencies:
  # apollovm: ^0.0.44
  apollovm: 
    path: ../apollovm_dart
  bonsai: ^1.2.0
  collection: ^1.18.0
  filesize: ^2.0.1
  isolate_name_server: ^1.1.0
  lua_dardo:
    path: ../../LuaDardo
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  shelf_web_socket: ^1.0.4
  tribbles:
    path: ../tribbles
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
