name: server
description: A highly concurrent WS server built using Isolates Erlang-style
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.0.5

dependencies:
  filesize: ^2.0.1
  tribbles: ^1.0.1
  lua_dardo: ^0.0.5
  # temp only for ws client    
  web_socket_channel: ^2.4.0
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  shelf_web_socket: ^1.0.4    

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
